### PR TITLE
Feature/smart string

### PR DESCRIPTION
**Pull request by bluebill1049**
- intro `stringToKey` function, I haven't integrated with anything, the idea is a user can just write key like string and we convert them behind, so lead to better DX.

```diff
<TypedController
  as="textarea"
-  name={["nested", "uncontrolled", "test"] as const}
+  name={"nested.uncontrolled.test" as const}
  defaultValue=""
  rules={{ required: true }}
/>
```

- fix prettier so it's aligned with other repo
- putting all the logic functions into a folder

### CODE REVIEW

**Comment by bluebill1049** [comment]
also, think twice, why don't' we just make Contorller strictly typed?

**Comment by bluebill1049** [comment]
if we can already support the string as name part.

**Comment by bluebill1049** [comment]
oh, that's right, I completely miss the point! sorry about that...

**Comment by bluebill1049** [comment]
Wish TS can support run time someday...

**Comment by kotarella1110** [comment]
I also wish it.
If supported, I will fix the core lib Controller.

**Pull request closed without merging**
